### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by c2707413730** [YenalyLiew/Han1meViewer#139]
### 實際行為

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.pause()' on a null object reference
	at cn.jzvd.JZMediaSystem.lambda$pause$2$cn-jzvd-JZMediaSystem(JZMediaSystem.java:66)
	at cn.jzvd.JZMediaSystem$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.os.HandlerThread.run(HandlerThread.java:67)

### 預期行為

浏览时报错

### Han1meViewer version

v0.14.5+24042003

### Android version

Android 14

### Device

Redmi K50 Pro

**Comment by YenalyLiew** [comment]
收到

**Comment by rootsboots768** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findFocus()' on a null object reference
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.onStart(SpecialEffectsController.kt:762)
	at androidx.fragment.app.SpecialEffectsController.processStart(SpecialEffectsController.kt:420)
	at androidx.fragment.app.SpecialEffectsController.completeBack(SpecialEffectsController.kt:452)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:844)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:529)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:279)
	at androidx.activity.OnBackPressedDispatcher$3.invoke(OnBackPressedDispatcher.kt:130)
	at androidx.activity.OnBackPressedDispatcher$3.invoke(OnBackPressedDispatcher.kt:127)
	at androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1.onBackInvoked(OnBackPressedDispatcher.kt:395)
	at android.view.ViewRootImpl$NativePreImeInputStage.doOnBackKeyEvent(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$NativePreImeInputStage.onProcess(ViewRootImpl.java:7204)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6890)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10082)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10033)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9993)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10232)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:350)
	at android.os.Looper.loopOnce(Looper.java:187)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by NeKoOuO** [comment]
@rootsboots768 你的報錯不要貼在別人的 issue 底下 自己再開一個

**Comment by YenalyLiew** [comment]
> @rootsboots768 你的報錯不要貼在別人的 issue 底下 自己再開一個

是的，顺便说一下是在那个页面点击哪个按钮触发的
