### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xinzhisuodong** [YenalyLiew/Han1meViewer#142]
用的最新版，粘贴番名 泣かぬな 点击搜索就直接报错了

java.lang.IllegalStateException: Required value was null.
	at com.yenaly.han1meviewer.ui.adapter.HanimeSearchHistoryRvAdapter.onCreateViewHolder$lambda$2$lambda$0(HanimeSearchHistoryRvAdapter.kt:85)
	at com.yenaly.han1meviewer.ui.adapter.HanimeSearchHistoryRvAdapter.$r8$lambda$sOqQXz8xZweYvGA3ViY-xPUosSY(Unknown Source:0)
	at com.yenaly.han1meviewer.ui.adapter.HanimeSearchHistoryRvAdapter$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7514)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:7491)
	at android.view.View.access$3600(View.java:846)
	at android.view.View$PerformClick.run(View.java:28733)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by YenalyLiew** [comment]
下版本修复，如果再出现这问题从这里告诉我
