### ISSUE TITLE
打开观看历史，报错

### ISSUE THREAD

**Issue by Ayaka-love** [YenalyLiew/Han1meViewer#146]
### 實際行為

打开观看历史。点击了几个视频，提示播放地址无效，在以后弹窗此错误，点击复制后闪退android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@bad338 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1705)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:451)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:325)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:186)
	at android.app.Dialog.show(Dialog.java:363)
	at com.yenaly.han1meviewer.ui.activity.LoginActivity$LoginDialog.show(LoginActivity.kt:200)
	at com.yenaly.han1meviewer.ui.activity.LoginActivity$initWebView$1$1.onReceivedError(LoginActivity.kt:135)
	at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:339)
	at WV.XL.e(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:70)
	at WV.j6.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:406)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 預期行為

预期未正常播放

### Han1meViewer version

v0.14.8

### Android version

安卓14

### Device

小米13pro

**Comment by YenalyLiew** [comment]
你是不是点击过一次登录，然后没登录就关闭那个页面了

**Comment by Ayaka-love** [comment]
> 你是不是点击过一次登录，然后没登录就关闭那个页面了

今天打开软件，加载不出来，然后瞎点点进了历史，点了几下就这样了，应该是没有点过登录

**Comment by crnkv** [comment]
服务器被攻击了：
https://hostloc.com/thread-1311613-1-1.html

**Comment by YenalyLiew** [comment]
> 服务器被攻击了：
> https://hostloc.com/thread-1311613-1-1.html

跟我没关系哦

**Comment by Hearing-Loss** [comment]
难怪打不开了，我还以为我的梯子被封IP了

**Comment by NeKoOuO** [comment]
已修復

**Comment by YenalyLiew** [comment]
> 已修復

bug没修复，webview内存泄漏问题很麻烦

**Comment by NeKoOuO** [comment]
> > 已修復
> 
> bug没修复，webview内存泄漏问题很麻烦
沒有拉我是說網站
