### ISSUE TITLE
点击删除后闪退报错了

### ISSUE THREAD

**Issue by xinzhisuodong** [YenalyLiew/Han1meViewer#158]
### 實際行為

点击删除直接就闪退报错了
![IMG_20240615_030513](https://github.com/YenalyLiew/Han1meViewer/assets/162891518/314746a0-93fe-4e43-bfdf-47279c05e853)
![Screenshot_2024-06-15-03-02-59-843_com yenaly han1meviewer](https://github.com/YenalyLiew/Han1meViewer/assets/162891518/554d3770-095a-477a-8833-32dd7b83c5ad)

### 預期行為

使用删除

### Han1meViewer version

v0.14.8+24052309

### Android version

11

### Device

MI9

### 其他

java.lang.IllegalStateException: Required value was null.
	at com.yenaly.han1meviewer.ui.adapter.HanimeDownloadedRvAdapter.onCreateViewHolder$lambda$6$lambda$1(HanimeDownloadedRvAdapter.kt:150)
	at com.yenaly.han1meviewer.ui.adapter.HanimeDownloadedRvAdapter.$r8$lambda$tjnZLXPv74jCBPbcMEL_ruBxNl8(Unknown Source:0)
	at com.yenaly.han1meviewer.ui.adapter.HanimeDownloadedRvAdapter$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7514)
	at android.view.View.performClickInternal(View.java:7491)
	at android.view.View.access$3600(View.java:846)
	at android.view.View$PerformClick.run(View.java:28733)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by YenalyLiew** [comment]
询问一下，报错重启后你删除的那个还在不在

**Comment by xinzhisuodong** [comment]
> 询问一下，报错重启后你删除的那个还在不在

当时上下划找了下，正常删除了
