### ISSUE TITLE
大概bug

### ISSUE THREAD

**Issue by osp-is** [YenalyLiew/Han1meViewer#170]
### 實際行為

黑屏卡出无法后台存在多次

### 預期行為

60g后频繁卡出android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@6bf4da2 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1185)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:418)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at android.app.Dialog.show(Dialog.java:383)
	at com.yenaly.han1meviewer.ui.activity.LoginActivity$LoginDialog.show(LoginActivity.kt:200)
	at com.yenaly.han1meviewer.ui.activity.LoginActivity$initWebView$1$1.onReceivedError(LoginActivity.kt:135)
	at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:337)
	at WV.uO.e(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:70)
	at WV.Z6.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:406)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8300)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

第二个：java.lang.IllegalArgumentException: Navigation action/destination com.yenaly.han1meviewer:id/action_homeSettingsFragment_to_playerSettingsFragment cannot be found from the current destination Destination(com.yenaly.han1meviewer:id/playerSettingsFragment) class=com.yenaly.han1meviewer.ui.fragment.settings.PlayerSettingsFragment
	at androidx.navigation.NavController.navigate(NavController.kt:1691)
	at androidx.navigation.NavController.navigate(NavController.kt:1609)
	at androidx.navigation.NavController.navigate(NavController.kt:1591)
	at androidx.navigation.NavController.navigate(NavController.kt:1574)
	at com.yenaly.han1meviewer.ui.fragment.settings.HomeSettingsFragment.onPreferencesCreated$lambda$4(HomeSettingsFragment.kt:145)
	at com.yenaly.han1meviewer.ui.fragment.settings.HomeSettingsFragment.$r8$lambda$TU1PsnWfeMrcZSyI5CYYTyY-Y9M(Unknown Source:0)
	at com.yenaly.han1meviewer.ui.fragment.settings.HomeSettingsFragment$$ExternalSyntheticLambda14.onPreferenceClick(D8$$SyntheticClass:0)
	at androidx.preference.Preference.performClick(Preference.java:1200)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference$1.onClick(Preference.java:182)
	at android.view.View.performClick(View.java:7505)
	at android.view.View.performClickInternal(View.java:7477)
	at android.view.View.access$3600(View.java:824)
	at android.view.View$PerformClick.run(View.java:28668)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8300)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

### Han1meViewer version

v0.14.8+24052309

### Android version

Android 11

### Device

vivo S

**Comment by YenalyLiew** [comment]
第一个问题大概解决了，如果你实在忍受不了，你去开启CI更新渠道更新一下就可以解决了，不想开可以再关闭
第二个我看看咋回事
