### ISSUE TITLE
搜索时报错

### ISSUE THREAD

**Issue by axlmly** [YenalyLiew/Han1meViewer#176]
不能稳定复现，暂时无法判断复现方法。
主页搜索时报错。
java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: QuickViewHolder{b830cd4 position=-1 id=-1, oldPos=-1, pLpos:-1 removed tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{c02beb0 VFED..... ........ 0,157-1388,314 #7f080242 app:id/rv_history}, adapter:com.yenaly.han1meviewer.ui.adapter.HanimeSearchHistoryRvAdapter@c34cca8, layout:androidx.recyclerview.widget.LinearLayoutManager@296f943, context:com.yenaly.han1meviewer.ui.activity.SearchActivity@1a62b18
	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:7077)
	at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1597)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13655)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:14157)
	at androidx.recyclerview.widget.SimpleItemAnimator.dispatchAddFinished(SimpleItemAnimator.java:312)
	at androidx.recyclerview.widget.DefaultItemAnimator$5.onAnimationEnd(DefaultItemAnimator.java:251)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:711)
	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at android.animation.Animator.callOnList(Animator.java:669)
	at android.animation.Animator.notifyListeners(Animator.java:608)
	at android.animation.Animator.notifyEndListeners(Animator.java:633)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1566)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1654)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1176)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1614)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by YenalyLiew** [comment]
我也复现了一次，然后就没复现了，不知道咋回事
