### ISSUE TITLE
添加打开链接bug反馈

### ISSUE THREAD

**Issue by xianren152** [YenalyLiew/Han1meViewer#197]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.settings.APP_OPEN_BY_DEFAULT_SETTINGS cat=[android.intent.category.DEFAULT] dat=package: flg=0x40800000 cmp=com.android.settings/.applications.InstalledAppOpenByDefaultActivity } from ProcessRecord{ee80236 21581:com.yenaly.han1meviewer/u0a239} (pid=21581, uid=10239) requires android.permission.OPEN_APP_OPEN_BY_DEFAULT_SETTINGS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
	at android.os.Parcel.createException(Parcel.java:3055)
	at android.os.Parcel.readException(Parcel.java:3038)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2904)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
	at android.app.Activity.startActivityForResult(Activity.java:5844)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
	at android.app.Activity.startActivityForResult(Activity.java:5802)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:683)
	at android.app.Activity.startActivity(Activity.java:6300)
	at android.app.Activity.startActivity(Activity.java:6267)
	at com.yenaly.han1meviewer.ui.fragment.settings.HomeSettingsFragment.showApplyDeepLinksDialog$lambda$34$lambda$33(HomeSettingsFragment.kt:321)
	at com.yenaly.han1meviewer.ui.fragment.settings.HomeSettingsFragment.$r8$lambda$pzDGO6d9im6tYo-scItnzixq2Dk(Unknown Source:0)
	at com.yenaly.han1meviewer.ui.fragment.settings.HomeSettingsFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9228)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1340)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1436)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:974)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1640)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1575)

**Comment by YenalyLiew** [comment]
请问是点击什么触发的？

**Comment by YenalyLiew** [comment]
提供下安卓版本和手机型号

**Comment by xianren152** [comment]
> 提供下安卓版本和手机型号

安卓版本：安卓14
手机型号：红魔9pro
系统版本：RedMagicOS9.0.31_NX769J

**Comment by xianren152** [comment]
> 请问是点击什么触发的？

设置中“应用深层链接”内的“前往设置”

**Comment by YenalyLiew** [comment]
你的机型好像不支持直接从app中打开这个，你可以在设置里自行寻找然后添加链接
