### ISSUE TITLE
全面屏手势返回bug

### ISSUE THREAD

**Issue by 116214MIX** [YenalyLiew/Han1meViewer#220]
### 實際行為

我点进一部影片，全面屏手势想返回主页，黑屏报告bug

### 預期行為

我在主页点进影片，可以正常返回上个页面(我用左上角的摁键可以正常返回）

### Han1meViewer version

0.15.0+24092112

### Android version

Android 14

### Device

Xiaomi 12T Pro

### 其他

java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$1(WindowOnBackInvokedDispatcher.java:353)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$jWVwe-YeLRxW3tAMLuWZynG6e1k(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8772)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by 116214MIX** [comment]
我在我自己系统中切换不了经典导航键，不知道是不是有相关bug影响到了软件的运行，已root

**Comment by YenalyLiew** [comment]
全面屏手势是指什么，从屏幕边缘左划返回吗

**Comment by YenalyLiew** [comment]
你用的开源阅读叫什么名字

**Comment by 116214MIX** [comment]
我解决了，不是软件的问题，我换了一个系统桌面不报错误了

**Comment by 116214MIX** [comment]
https://github.com/gedoor/legado![Screenshot_2024-09-25-00-08-15-830_io.legado.app.release.jpg](https://github.com/user-attachments/assets/29f06f72-44b7-40ec-a3ee-7c5ddebfcb3b)

> 你用的开源阅读叫什么名字

**Comment by 116214MIX** [comment]
https://github.com/gedoor/legado> 你用的开源阅读叫什么名字
![Screenshot_2024-09-25-00-08-15-830_io.legado.app.release.jpg](https://github.com/user-attachments/assets/fa96bdae-726a-4ec7-a9bb-c3b1409769a1)

**Comment by YenalyLiew** [comment]
嗯嗯，应该是开启了预测性返回动画的问题
从开发者模式关闭或开启下试试
<img width="692" alt="image" src="https://github.com/user-attachments/assets/70b62bde-de59-4255-b438-9ccbb7a5d3e3">

**Comment by YenalyLiew** [comment]
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/a23724aa-70b3-4656-ae70-76e9af4722d9">
是不是你，崩了这么多次😄

**Comment by YenalyLiew** [comment]
不对，你是12T，这个人是11T，一模一样的错误

**Comment by YenalyLiew** [comment]
你可以更新一下ci渠道中的最新版本，我把这个功能关闭了，应该没问题了
