### ISSUE TITLE
下载界面点击右上角按钮后闪退

### ISSUE THREAD

**Issue by axlmly** [YenalyLiew/Han1meViewer#51]
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/graphics/drawable/DrawableWrapper;
	at androidx.appcompat.widget.MenuPopupWindow.createDropDownListView(MenuPopupWindow.java:80)
	at androidx.appcompat.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1179)
	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java:664)
	at androidx.appcompat.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:181)
	at androidx.appcompat.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:208)
	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:296)
	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:182)
	at androidx.appcompat.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:144)
	at androidx.appcompat.widget.ActionMenuPresenter.onSubMenuSelected(ActionMenuPresenter.java:310)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchSubMenuSelected(MenuBuilder.java:314)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1008)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7798)
	at android.view.View.performClickInternal(View.java:7775)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31125)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassNotFoundException: androidx.appcompat.graphics.drawable.DrawableWrapper
	... 26 more

**Comment by YenalyLiew** [comment]
下一版本修复
