### ISSUE TITLE
在跳转页面与下载重复多次后闪退

### ISSUE THREAD

**Issue by axlmly** [YenalyLiew/Han1meViewer#63]
android.database.sqlite.SQLiteFullException: database or disk is full (code 13 SQLITE_FULL)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:757)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.kt:75)
	at androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.kt:553)
	at androidx.room.RoomDatabase.endTransaction(RoomDatabase.kt:543)
	at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:351)
	at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:289)
	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:252)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:135)
	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by YenalyLiew** [comment]
储存空间满了
