### ISSUE TITLE
打开失败

### ISSUE THREAD

**Issue by jiakelu086** [YenalyLiew/Han1meViewer#89]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yenaly.han1meviewer/com.yenaly.han1meviewer.ui.activity.MainActivity}: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4607)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4805)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:118)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:153)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:104)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3064)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9639)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:595)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at com.yenaly.yenaly_libs.base.YenalyActivity.onCreate(SourceFile:26)
	at android.app.Activity.performCreate(Activity.java:9032)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4589)
	... 12 more
![Uploading Screenshot_20240323_111537_com.yenaly.han1meviewer.jpg…]()

**Comment by YenalyLiew** [comment]
打开的哪个节目

**Comment by jiakelu086** [comment]
软件点进去就报错了

**Comment by YenalyLiew** [comment]
安卓版本是什么？

**Comment by jiakelu086** [comment]
![Uploading Screenshot_20240323_165454_com.android.settings.jpg…]()

**Comment by jiakelu086** [comment]
![Screenshot_20240323_165454_com android settings](https://github.com/YenalyLiew/Han1meViewer/assets/164594042/4940b3b8-9303-4f9f-91df-5158978e2cd7)

**Comment by YenalyLiew** [comment]
我去，我也遇到这问题了

**Comment by jiakelu086** [comment]
可以了 大佬NB
